name: Create Release on Merge

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      - name: Extract Version from Branch
        id: extract_version
        run: |
          BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oP 'release/\K.*')
          echo "VERSION=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish_folder/GithubActionDotnetTestSource.zip  # Path to your published app (output folder)
          asset_name: GithubActionDotnetTestSource.zip
          asset_content_type: application/zip